SPPO-Llama-3-Instruct-8B-Iter1-score_gp_8b-0.002:
  completions_kwargs:
    batch_size: 900
    # do_sample: true
    use_beam_search: false
    max_new_tokens: 4096
    model_kwargs:
      dtype: bfloat16
    model_name: /cephfs/xukangping/code/SPPO/checkpoints/Llama-3-8B-Instruct-SPPO-score-Iter1_gp_8b-table-0.002
    stop_token_ids:
    - 128001
    - 128009
    temperature: 0.9
    top_p: 1.0
  fn_completions: vllm_local_completions
  pretty_name: SPPO-Llama-3-Instruct-8B-Iter1-score_gp_8b-0.002
  prompt_template: SPPO-Llama-3-Instruct-8B-PairRM/prompt.txt